name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: 1//0gHQjPojPuS4UCgYIARAAGBASNwF-L9Ir5JXBjJPiXJ8DC61GNBcn2zw6P_G3S9t7LUxPJM4T6vd0ANvuRkCJJE1VDzXtHVyWcVo
          FIREBASE_PROJECT: my-app-c980d
