name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        uses: lowply/deploy-firebase@v0.0.2
        run: npm run deploy-demo
      - name: Build2
        uses: lowply/deploy-firebase@v0.0.2
        run: npm run deploy-prod